version: "3.7"

services:
  nginx:
    container_name: clean_nginx
    image: nginx:1.19.6-alpine
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    container_name: clean_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app